# Makes artifactory the default registry and saves passing --registry parameter
[registry]
default = "innersource"

[registries.innersource]
index = "sparse+https://BASE_URL/artifactory/api/cargo/innersource-cargo-local/index/"

[registries.crates-remote]
index = "sparse+https://BASE_URL/artifactory/api/cargo/crates-remote/index/"
