# Makes artifactory the default registry and saves passing --registry parameter
[registry]
default = "innersource"

[registries.innersource]
index = "sparse+https://tomjfrog.jfrog.io/artifactory/api/cargo/innersource-cargo-local/index/"

[registries.crates]
index = "sparse+https://tomjfrog.jfrog.io/artifactory/api/cargo/crates-remote/index/"
