name: Push NPM Build to Artifactory
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      # This action checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        working-directory: ./npm

      # This action sets up the JFrog CLI with the Artifactory URL and access token     
      - name: Get JFrog CLI -v4   
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      
      # This command adds a new server configuration to the JFrog CLI   
      - run: |
          export SERVER_ID="test"
          jf -v
          jf c add $SERVER_ID --url=$URL --access-token=$ACCESS_TOKEN --interactive=false

      - run: |
          jf rt ping
          jf npmc --repo-deploy=ghjfdemo-ghjf-npm-virt --repo-resolve=ghjfdemo-ghjf-npm-remote
          jf npm install --build-name=ghdemo-npm-build --build-number=1.0.${{github.run_number}}
          jf rt build-add-git ghdemo-npm-build 1.0.${{github.run_number}}
          jf rt build-collect-env ghdemo-npm-build 1.0.${{github.run_number}}
          jf rt npm-publish --build-name=ghdemo-npm-build --build-number=1.0.${{github.run_number}}
          jf rt build-publish ghdemo-npm-build 1.0.${{github.run_number}}
          jf rt build-scan ghdemo-npm-build 1.0.${{github.run_number}}
          jf rt build-promote ghdemo-npm-build 1.0.${{github.run_number}} ghjfdemo-ghjf-npm-prod-local  --status=production
