on:
  push:
    branches:
    - nuget-sample-library
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      JF_URL: https://${{ vars.JF_URL }}/
    defaults:
      run:
        working-directory: ./nuget/sample-library
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
   # - name: Set VERSION variable from tag
  #    run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ vars.VERSION }}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ vars.VERSION }} --no-build --output .
   # - name: Push
    # run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN}
