name: Rust & Cargo Quotes Application
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}
  CARGO_REGISTRIES_INNERSOURCE_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}
  CARGO_REGISTRIES_JFROGQUOTES_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}

# The default working-directory is needed, due to all example Actions specs residing in the same directory, but each
# package example code is in different directories.  This `default` config saves us the effort of setting a
# `working-directory` on each step.
defaults:
  run:
    shell: bash
    working-directory: ./rust/jfrog_app

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Cargo installation
        run: cargo --version

      - name: Build Application
        run: cargo build --release --verbose

      - name: Publish Application To Artifactory
        run: cargo publish --token "Bearer ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}"