name: Rust & Cargo Build and Deploy
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  AUTHENTICATION_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Cargo installation
        run: 'cargo --version'
      - name: Build
        run: 'cargo build --release --verbose'
      - name: Publish To Artifactory
        run: "cargo publish --registry artifactory --token \"$AUTHENTICATION_TOKEN\""